### ISSUE TITLE
Console gem is used but not in the gemspec

### ISSUE THREAD

**Issue by zach-taylor** [socketry/traces#14]
The `console` gem is required [here](https://github.com/socketry/traces/blob/main/lib/traces/backend.rb#L6) but the gem isn't in the gemspec.

**Comment by ioquatix** [comment]
That is a good point.

I'd be okay to add it.

However, not everyone who pulls in the traces gem will want to use it or have a specific backend in mind. I think in this case, it's mostly for convenience, but perhaps we should move this to `traces-backend-console` as a separate gem.

**Comment by ioquatix** [comment]
You are correct. I have decided to change that to use `Kernel#warn` instead, so the `console` gem is no longer a required dependency. In addition, I changed `console` gem to intercept `Kernel#warn`: https://github.com/socketry/console/commit/643dd0ffcc1bc916fc351f5477332038cc066b72

Thanks for your report.
